# Generated by Django 4.0.2 on 2022-04-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_lissa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsales',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='price'),
        ),
    ]
